### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by ghost** [elseytd/TheAurorian#3]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  FutureMC (future-mc-0.1.13.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  midnight (themidnight-0.3.5.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.4-core.jar)
  ratscore (rats-3.2.4.jar)
  Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 1/2/20 1:01 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Aurorian (theaurorian)
Caused by: java.lang.IllegalArgumentException: Failed to register dimension for id 24, One is already registered
	at net.minecraftforge.common.DimensionManager.registerDimension(DimensionManager.java:134)
	at com.elseytd.theaurorian.TADimensions.registerDimensions(TADimensions.java:22)
	at com.elseytd.theaurorian.TADimensions.init(TADimensions.java:14)
	at com.elseytd.theaurorian.Proxy.CommonProxy.preInit(CommonProxy.java:42)
	at com.elseytd.theaurorian.Proxy.ClientProxy.preInit(ClientProxy.java:20)
	at com.elseytd.theaurorian.TAMod.preInit(TAMod.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1267168480 bytes (1208 MB) / 3892314112 bytes (3712 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 51 mods loaded, 51 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version                     | Source                                                    | Signature                                |
	|:----- |:-------------------------- |:--------------------------- |:--------------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                  | 1.12.2                      | minecraft.jar                                             | None                                     |
	| LCH   | mcp                        | 9.42                        | minecraft.jar                                             | None                                     |
	| LCH   | FML                        | 8.0.99.99                   | forge-1.12.2-14.23.5.2847.jar                             | None                                     |
	| LCH   | forge                      | 14.23.5.2847                | forge-1.12.2-14.23.5.2847.jar                             | None                                     |
	| LCH   | futuremccore               | 0.1.12                      | minecraft.jar                                             | None                                     |
	| LCH   | techguns_core              | 1.12.2-1.0                  | minecraft.jar                                             | None                                     |
	| LCH   | movillages                 | 1.5.4                       | [1.12]MoVillages-1.5.4.jar                                | None                                     |
	| LCH   | jei                        | 4.15.0.291                  | jei_1.12.2-4.15.0.291.jar                                 | None                                     |
	| LCH   | abyssalcraft               | 1.9.15                      | AbyssalCraft-1.12.2-1.9.15 (1).jar                        | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | aoa3                       | 3.1.2.b                     | AoA3-3.1.2.b.jar                                          | None                                     |
	| LCH   | atum                       | 2.0.16                      | Atum-1.12.2-2.0.16.jar                                    | None                                     |
	| LCH   | bookshelf                  | 2.3.585                     | Bookshelf-1.12.2-2.3.585.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | casinocraft                | v06                         | CasinoCraft_1.12.2_v06.jar                                | None                                     |
	| LCH   | chaotica                   | 4.8.5                       | Chaotica_v4.8.51fixed[1.12.2].jar                         | None                                     |
	| LCH   | ctm                        | MC1.12.2-1.0.1.30           | CTM-MC1.12.2-1.0.1.30.jar                                 | None                                     |
	| LCH   | customnpcs                 | 1.12                        | CustomNPCs_1.12.2-(01Oct19).jar                           | None                                     |
	| LCH   | darknesslib                | 1.0.0                       | DarknessLib-1.12.2-1.0.0.jar                              | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | emergingtechnology         | 1.2.13-beta                 | EmergingTechnology-1.12.2-1.2.13-beta.jar                 | None                                     |
	| LCH   | erebus                     | 1.0.31                      | Erebus-1.0.31.jar                                         | None                                     |
	| LCH   | cfm                        | 6.3.1                       | furniture-6.3.1-1.12.2.jar                                | None                                     |
	| LCH   | minecraftfuture            | 0.1.13                      | future-mc-0.1.13.jar                                      | None                                     |
	| LCH   | gaiadimension              | 1.0.5                       | gaiadimension-1.12.2-1.0.5.jar                            | None                                     |
	| LCH   | goodnightsleep             | 0.2.2                       | good-nights-sleep-1.12.2-v0.2.2.jar                       | None                                     |
	| LCH   | grue                       | 1.6.0                       | Grue-1.12.2-1.6.0.jar                                     | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCH   | huntingdim                 | 1.0.42                      | HuntingDimension-1.12.2-1.0.42.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | incontrol                  | 3.9.16                      | incontrol-1.12-3.9.16.jar                                 | None                                     |
	| LCH   | interdimensional_traveller | 0.4.0                       | Interdimensional_Traveller+v+0.4.0.jar                    | None                                     |
	| LCH   | journey                    | 1.0.5.1                     | journey-1.0.5.1.jar                                       | None                                     |
	| LCH   | jaff                       | 1.7_for_1.12                | JustAFewFish-1.7_for_1.12.jar                             | None                                     |
	| LCH   | justenoughdimensions       | 1.6.0-dev.20191019.172643   | justenoughdimensions-1.12.2-1.6.0-dev.20191019.172643.jar | 2b03e1423915a189b8094816baa18f239d576dff |
	| LCH   | jeid                       | 1.0.3-48                    | JustEnoughIDs-1.0.3-48.jar                                | None                                     |
	| LCH   | moolands                   | 1.1.6                       | moolands-1.12.2-1.1.6.jar                                 | None                                     |
	| LCH   | moreplayermodels           | 1.12.2                      | MorePlayerModels_1.12.2-(05Dec19).jar                     | None                                     |
	| LCH   | neat                       | 1.4-17                      | Neat+1.4-17.jar                                           | None                                     |
	| LCH   | harvestcraft               | 1.12.2zb                    | Pam's+HarvestCraft+1.12.2zf.jar                           | None                                     |
	| LCH   | patchouli                  | 1.0-20                      | Patchouli-1.0-20.jar                                      | None                                     |
	| LCH   | raolcraft                  | 2.2.2                       | RaolCraft+Omega+2.2.2+(MC+1.12.2).jar                     | None                                     |
	| LCH   | llibrary                   | 1.7.19                      | llibrary-1.7.19-1.12.2.jar                                | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | rats                       | 3.2.4                       | rats-3.2.4.jar                                            | None                                     |
	| LCH   | merpig                     | 1.12.2-0.0.1.20190504132448 | SBM-Merpig-1.12.2-0.0.1b20190504132456.jar                | None                                     |
	| LCH   | supertnt                   | 1.0.1                       | SuperTNT-1.12.2-1.0.1.jar                                 | None                                     |
	| LCH   | techguns                   | 2.0.2.0                     | techguns-1.12.2-2.0.2.0_pre3.1.jar                        | None                                     |
	| LCH   | beneath                    | 1.7.0                       | The+Beneath-1.12.2-1.7.0.jar                              | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCE   | theaurorian                | 1.12.2-Beta                 | theaurorian-1.12.2-beta-dec2919.jar                       | None                                     |
	| LC    | thecrystallia              | 1.0.8                       | TheCrystallia+1.0.9+[1.12.2].jar                          | None                                     |
	| LC    | microworld                 | 1.3.2                       | TheMicroWorld-1.3.2-1.12.2.jar                            | None                                     |
	| LC    | twilightforest             | 3.10.1013                   | twilightforest-1.12.2-3.10.1013-universal.jar             | None                                     |
	| LC    | xaerominimap               | 1.19.5                      | Xaeros_Minimap_1.19.5_Forge_1.12.jar                      | None                                     |
	| LC    | xaeroworldmap              | 1.5.2                       | XaerosWorldMap_1.5.2_Forge_1.12.jar                       | None                                     |
	| LC    | thebetweenlands            | 3.5.4                       | TheBetweenlands-3.5.4-universal.jar                       | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| LC    | midnight                   | 0.3.5                       | themidnight-0.3.5.jar                                     | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
FutureMC (future-mc-0.1.13.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-48.jar)
  org.dimdev.jeid.JEIDTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
midnight (themidnight-0.3.5.jar)
  com.mushroom.midnight.core.transformer.MidnightClassTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.5.4-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
ratscore (rats-3.2.4.jar)
  com.github.alexthe666.rats.server.misc.RatsRuntimePatcher
Techguns Core (techguns-1.12.2-2.0.2.0_pre3.1.jar)
  techguns.core.TechgunsASMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7263' Renderer: 'Intel(R) UHD Graphics 630'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 26.20.100.7263
	OpenGlRenderer: Intel(R) UHD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by ghost** [comment]
Never mind, I just realized that it has conflicting dim ids.
